"""Archive the exact flash files/addresses generated by ESP-IDF."""
import json
from pathlib import Path
import zipfile

root = Path(__file__).resolve().parents[1]
build = root / 'firmware/build'
metadata = json.loads((build / 'flasher_args.json').read_text())
release = root / 'release'
release.mkdir(exist_ok=True)
with zipfile.ZipFile(release / 'RemoteKeyMapper-firmware-esp32.zip', 'w', zipfile.ZIP_DEFLATED) as archive:
    for name in [*metadata['flash_files'].values(), 'flash_args', 'flasher_args.json']:
        archive.write(build / name, name)
    archive.write(root / 'docs/FIRMWARE.md', 'README.md')
print('Packaged ESP32 firmware and generated flash metadata')
